### ISSUE TITLE
Add the ability to add to current grafana install 

### ISSUE THREAD

**Issue by 00o-sh** [dinger1986/TRMM-Grafana#11]
I currently use grafana to monitor other resources is it possible to add to a current install

**Comment by dinger1986** [comment]
Existing grafana instance? If so no, you can use the install script as a guide but will need ports opened etc all parts I wouldn't suggest.

**Comment by 00o-sh** [comment]
If grafana is hosted internally which it is in my case there is no ports involved

**Comment by dinger1986** [comment]
Ok up to yourself
