### ISSUE TITLE
Datasource not found

### ISSUE THREAD

**Issue by Shamutik** [dinger1986/TRMM-Grafana#14]
Hello! I installed everything according to the instructions and successfully get into the grafana interface. But when I switch to any of the dashboard tactical rmm I get pop-ups with an error
"Templating
Failed to upgrade legacy queries Datasource was not found"

DataSource did not change. default PostgreSQL. When you click Save and test button writes that
Database Connection OK
![error](https://user-images.githubusercontent.com/13059023/162853428-b18914de-469c-4bfe-aba1-6ce2a479ff48.jpg)

**Comment by ninjamonkey198206** [comment]
That's probably my fault. In the middle of updating these and the instructions. Let me check something.

**Comment by ninjamonkey198206** [comment]
Assuming everything else was done per the current instructions (that I forgot to include this in when I updated them, sorry), you should just need to edit your datasource settings. The current versions use a variable that requires a certain datasource name. The T-RMM postgresql datasource needs to be named TacticalRMM.

The idea was to eliminate the datasource UID from the equation in the panels, and the requirement for it to be the default datasource.
![Screenshot 2022-04-06 114312](https://user-images.githubusercontent.com/24654529/162855065-d7e660f4-dd42-4b3b-8a24-9b2c519387d1.png)

**Comment by ninjamonkey198206** [comment]
@Shamutik Instructions have been updated, as has the install script. Please see the above and the readme, and let me know if that resolves your issue.

**Comment by Shamutik** [comment]
@ninjamonkey198206 changing the name PostgreSQL to TacticalRMM really helped. now everything is displayed correctly. thank you
