### ISSUE TITLE
CPU/Memory/Disk usage graphs on T-RMM Agent Dashboard don't populate

### ISSUE THREAD

**Issue by manc74** [dinger1986/TRMM-Grafana#17]
Fresh install on bare metal (Ubuntu 20.04) following the install instructions.

The default agent dashboard doesn't populate the graphs:
![grafina](https://user-images.githubusercontent.com/68019920/167386653-1436cced-b452-4da4-b792-882c1a5cf585.png)

Have I done something wrong? All other data in the dashboards load ok.

**Comment by ninjamonkey198206** [comment]
Do you have the CPU and memory checks enabled on the agents?

**Comment by ninjamonkey198206** [comment]
FYI, those won't work on Linux agents yet, as the checks don't exist for Linux yet.

**Comment by manc74** [comment]
/facepalm ;)

Checks enabled and working! Thanks.

**Comment by ninjamonkey198206** [comment]
Ha, no worries.

**Comment by ventra007** [comment]
Hi,

I must mention that I ran into this issue as well. My problem though was that the CPU and Memory checks was configured through an automation policy that applied it, and these are not pulling through. Only when I add the check manually does it appear.
