### ISSUE TITLE
Queries reference non-unique agent hostname

### ISSUE THREAD

**Issue by Zebble** [dinger1986/TRMM-Grafana#20]
Queries should be changed to reference the unique agent_id instead of hostname.

**Comment by Zebble** [comment]
This is now addressed in Pull Request 19:

https://github.com/dinger1986/TRMM-Grafana/pull/19

**Comment by dinger1986** [comment]
have replied to the PR

**Comment by dinger1986** [comment]
I replied on the PR and thought you would do a PR for a new dashboard :)
