### ISSUE TITLE
Password authentication failed for dbreader

### ISSUE THREAD

**Issue by conlan0** [dinger1986/TRMM-Grafana#23]
I followed the installation instructions on my server that has my tactical install.(which is a VMware image of Ubuntu 20.04.4 Desktop) When I got to the configurations in the grafana UI I had everything set exactly as it showed and received and error "db query error: pq: password authentication failed for user "dbreader"".
 ![image](https://user-images.githubusercontent.com/87742085/195399345-cf0bfbaa-4633-4209-96d1-84a664b9448c.jpeg)
 ![image](https://user-images.githubusercontent.com/87742085/195399394-5a6fa2ec-db87-47f5-a08a-8979693210b8.jpeg)

**Comment by dinger1986** [comment]
I guess you ran the install script more than once, in the main repo there's instructions for install and troubleshooting and one is how to reset/recover the password.
