### ISSUE TITLE
Same as #7 and #9

### ISSUE THREAD

**Issue by lakotajames** [dinger1986/TRMM-Grafana#24]
Permission issue for the letsencrypt cert.  chmod 777 on the cert doesn't fix it though.

logger=server t=2022-11-03T20:29:13.155036798Z level=error msg="Stopped background service" service=*api.HTTPServer reason="open /etc/letsencrypt/live/(domain)/fullchain.pem: permission denied"

ls -la:
lrwxrwxrwx 1 tactical tactical 38 Oct 24 20:52 /etc/letsencrypt/live/(domain)/fullchain.pem -> ../../archive/(domain)/fullchain1.pem

**Comment by dinger1986** [comment]
for the first step did you put in rmm.yourdomain or just yourdomain.com and the second rmm.yourdomain.com or yourdomain.com?

#7 was due to this #2 has the resolve on it.

As it doesnt sound like cert permissions

**Comment by dinger1986** [comment]
issue resolved, grafana service is set to run as the tactical user, swapped it now and it works fine, the username was ignored for the service which is shouldnt have been
