### ISSUE TITLE
debian installation fails to start grafana service because directory has reference/shortcut

### ISSUE THREAD

**Issue by farleyoc** [dinger1986/TRMM-Grafana#26]
In the /etc/letsencrypt/live/example.com/ directory contains reference/shortcuts to the certificates located in another directory
![Screenshot 2022-11-16 005843](https://user-images.githubusercontent.com/12927080/202096425-4402393c-c0bb-4ed2-ba6e-72c539f768d7.jpg)

This causes run error with permission denied to the certificates
![Screenshot 2022-11-16 010158](https://user-images.githubusercontent.com/12927080/202097790-ca63bfca-17a9-47c8-81f4-670fe5325a80.jpg)

Solution for my setup was to place a copy of the certificates in the "/etc/letsencrypt/live/example.com/" 
![Screenshot 2022-11-16 010756](https://user-images.githubusercontent.com/12927080/202097894-37961743-9f1a-4dd8-9a06-fdcd5def8072.jpg)

Not sure if there is a way to automate this or add into troubleshooting section of the readme?

**Comment by dinger1986** [comment]
That directory always has a reference/link I don't think that's why it didn't work as it's a symbolic link.

I'll need to test again so will do that soon.

**Comment by farleyoc** [comment]
I did a bare metal install with debian, then tactical rmm, then trmm-grafana. 

After digging through issue resolutions on github, I knew I hadn't made the typical mistake so I spun up a second fresh debian virtual machine install and closely followed each step thinking I missed something. Same error so I downloaded a copy of the certs and placed them in the folder and moved the references into a backup folder.

FYI

**Comment by dinger1986** [comment]
sounds similar to #24

**Comment by farleyoc** [comment]
Nope isn't similar to #24. I checked permissions and followed the directions for "rmm.yourdomain.com" then "yourdomain.com" before working on an alternative solution not provided in anywhere on github or google. I read every issue you responded to plus searched across the web.

**Comment by dinger1986** [comment]
That's ok, was just checking if it was related.

I'll take a look when I get a chance

**Comment by patzl93** [comment]
Got the same issue on debian, checked the other threads and permissions.
Hope you'll find some time

**Comment by dinger1986** [comment]
issue resolved, grafana service is set to run as the tactical user, swapped it now and it works fine, the username was ignored for the service which is shouldnt have been
