### ISSUE TITLE
"has_patches_pending" does not exist

### ISSUE THREAD

**Issue by farleyoc** [dinger1986/TRMM-Grafana#27]
I love this software and telling my I.T. friends about this. Only issue left is one error "has_patches_pending". Not sure if this is a task that needs to be setup on the agent like cpu and memory or something else. Can you point me in the direction to resolve this?

![image](https://user-images.githubusercontent.com/12927080/202877428-a1874336-a817-4507-97b2-c9b4f9a2912b.png)

![image](https://user-images.githubusercontent.com/12927080/202877474-966bdbd5-3387-4e7d-ac43-5a0186729be2.png)

**Comment by TiDjY35** [comment]
same problem

no information in database with tactical RMM v0.14.8

**Comment by dinger1986** [comment]
I have no idea, that dash was built by someone else, if you figure it out please do a PR. Btw @TiDjY35 you need to upgrade your TRMM :)
