### ISSUE TITLE
TV Dashboard - Show all overdue agents

### ISSUE THREAD

**Issue by Jinx-IT** [dinger1986/TRMM-Grafana#3]
Hello,

Instead of the "Errors" panel on TV Dashboard, would it possible to have an "Offline" panel that shows any number of overdue agents and then a list of which agents are offline below? I have tried messing around with some of the data and cannot find a way to get it to pull this info, I suppose the only work around would be having it detect when a overdue email alert is sent - but this isn't ideal. Any help would be greatly appreciated. 

Thanks

**Comment by dinger1986** [comment]
I need to delve more into the database and understand better how it all links together as this and some other requests should be easily implemented.

You could ask in #unsupported in the tactical discord chat and someone might give you some pointers
