### ISSUE TITLE
ERR_CONNECTION_REFUSED after install

### ISSUE THREAD

**Issue by verticalhost** [dinger1986/TRMM-Grafana#30]
Hi , 

after installing i got this on website

ERR_CONNECTION_REFUSED

It give me the action address but unable to acces on website with :3000

**Comment by dinger1986** [comment]
What errors do you get in the logs?

**Comment by verticalhost** [comment]
I dont see on documentation i can get's logs. 
It's just installed on my server but never give me error.

**Comment by dinger1986** [comment]
run the install script again and it should work fine, you will need to follow the troubleshooting steps to reset the postgres details but its just a step by step

**Comment by verticalhost** [comment]
I have re-downloaded and re-installed and got the same result but again no logs appear as error. 

I double checked and got this. 



./installg.sh: ligne 1076: data : commande introuvable
./installg.sh: ligne 1076: root_url : commande introuvable
./installg.sh: ligne 1076: 0 : commande introuvable
./installg.sh: ligne 1076: lax : commande introuvable
./installg.sh: ligne 1076: grafana_environment_info : commande introuvable

**Comment by dinger1986** [comment]
yeah those errors always come up but do nothing.

can you show the output of `ls -l /etc/grafana/`

**Comment by verticalhost** [comment]
tactical@debian:~$ ls -l /etc/grafana/
total 64
-rw-r--r-- 1 root     grafana   1834  4 jan 10:27 cert.pem
-rw-r--r-- 1 root     grafana   3749  4 jan 10:27 chain.pem
-rw-r--r-- 1 root     grafana   5583  4 jan 10:27 fullchain.pem
-rw-r--r-- 1 tactical tactical 33905  4 jan 10:27 grafana.ini
-rw-r----- 1 root     grafana   2594  3 jan 14:34 ldap.toml
-rw------- 1 root     grafana   1704  4 jan 10:27 privkey.pem
drwxr-xr-x 8 root     grafana   4096  3 jan 14:34 provisioning

**Comment by dinger1986** [comment]
ok, can you check grafana.ini that its using /etc/grafana/fullchain.pem as the certificate address? If not maybe just need to change that.

also you can do `sudo tail /var/log/grafana.grafana.log`

**Comment by verticalhost** [comment]
Yup it's supposed 
![image](https://user-images.githubusercontent.com/100486259/210591928-fb51279d-0c74-42a0-9725-e9c88119a238.png)
![image](https://user-images.githubusercontent.com/100486259/210592002-17eeb7f4-5358-4ae7-914b-d63a45ecc874.png)

Can i switch to this be cause it's used by T-RMM 

/etc/letsencrypt/live/MYWEBSITE.ca/

**Comment by verticalhost** [comment]
[grafana.log](https://github.com/dinger1986/TRMM-Grafana/files/10345424/grafana.log)

**Comment by dinger1986** [comment]
it was using the TRMM certs and that didnt work, its a strange grafana quirk and I built a trmm/grafana server from scratch last night to test and found the only way to do it was to move the certs and change the permissions

If you can provide the output of the logs that would help

**Comment by dinger1986** [comment]
please try `chmod 644 /etc/grafana/privkey.pem`

Then `systemctl restart grafana-server`

**Comment by verticalhost** [comment]
After i got that. 

Client sent an HTTP request to an HTTPS server.****
Never mind

**Comment by verticalhost** [comment]
The username and password i need it's same as T-RMM ?

**Comment by dinger1986** [comment]
no its admin/admin

**Comment by verticalhost** [comment]
Yeah lol i forgot it saying on install progress lol
Thanks everythings is set :D

**Comment by dinger1986** [comment]
if you have installed again you might need to reset the db login details https://github.com/dinger1986/TRMM-Grafana#troubleshooting
