### ISSUE TITLE
Error configuring client map

### ISSUE THREAD

**Issue by thiagopalacio** [dinger1986/TRMM-Grafana#31]
I create the python script as instructed, pass the arguments and it gives this error below:
Traceback (most recent call last):
  File "C:\ProgramData\TacticalRMM\2664578975.py", line 6, in <module>
    if len(str(sys.argv[2])) == 2:
IndexError: list index out of range

**Comment by dinger1986** [comment]
What python script?

**Comment by thiagopalacio** [comment]
https://raw.githubusercontent.com/dinger1986/TRMM-Grafana/a8e19f8a286cda043d8b06cac9592ee197c2dea2/Scripts/Map_getCoordinates.py

**Comment by dinger1986** [comment]
Did you put in your key etc?

**Comment by thiagopalacio** [comment]
Yes. I entered the api key
This script is multi platform, correct?
Tried to run on Windows and Linux.
On Linux it gives the error reported before.
In WIndows it gives this below: fork/exec C:\Program Files\TacticalAgent\py38-x64\python.exe: Incorrect parameter.
