### ISSUE TITLE
Cannot set variables

### ISSUE THREAD

**Issue by moose999** [dinger1986/TRMM-Grafana#32]
Hi,

I have followed the guide for baremetal setup.

I am unable to set the TacticalURL and GrafanaURL variables, and so the links on the dashboard do not work.

I have tried to set the variables in the included dashboards, but when I go to save, I get "This dashboard cannot be saved from the Grafana UI because it has been provisioned from another source."

I have copied the dashboards, and whilst I can save the new variables in the copies, and they appear in the drop-down menus at the top of the dashboards, whenerver I try and select them they just default back to the example URLs.

Can anyone suggest what I might have done wrong?

Many thanks!

**Comment by dinger1986** [comment]
can you provide screenshots?

**Comment by moose999** [comment]
Hi,

Here's a screengrab of my inability to save the 'default' dashboard: 

![image](https://github.com/dinger1986/TRMM-Grafana/assets/22505336/5e35c218-0e38-4297-aaa6-660d8b813e2b)

I think I mis-described the other issue  - whilst I can save the copied dashboard, the links in the various "stats" columns still point to the 'default' dashboards.

Many thanks,
Justin

**Comment by dinger1986** [comment]
now thats strange and not an issue I have had, what if you copy the json of the dash and create a new one then make your changes?
