### ISSUE TITLE
Ubuntu 22.04 Support

### ISSUE THREAD

**Issue by rytional** [dinger1986/TRMM-Grafana#35]
Not really an issue, more of a request. Are there plans to support Ubuntu 22.04 with the bare metal install?

**Comment by TheTechnologyStudio** [comment]
yea its not working for me either. says your system does not appear to be supported. I'm using 22.04 also.

**Comment by TheTechnologyStudio** [comment]
@dinger1986

**Comment by dinger1986** [comment]
Just comment it out, or run the steps in the script line by line. Really don't see the need to tag me

**Comment by dinger1986** [comment]
should work now

**Comment by TheTechnologyStudio** [comment]
./installg.sh: line 1: unexpected EOF while looking for matching `)'
./installg.sh: line 2: syntax error: unexpected end of file

**Comment by TheTechnologyStudio** [comment]
Still not working, Sorry.
