### ISSUE TITLE
Script broken [Solved]

### ISSUE THREAD

**Issue by TheTechnologyStudio** [dinger1986/TRMM-Grafana#37]
Hello Dinger1986. Regarding what you said in the other ticket about the commenting or removing the update check function, I did that before and I also tried the update you did last night around 3 mins ago and it is giving this error:

thetechdev@tacticalrmm:~$ ./installg.sh
./installg.sh: line 1: unexpected EOF while looking for matching `)'
./installg.sh: line 2: syntax error: unexpected end of file

![Screenshot_24](https://github.com/dinger1986/TRMM-Grafana/assets/19619093/31788c0c-9626-458b-81d8-9bc0849a2961)

**Comment by dinger1986** [comment]
Is there a need to open a new ticket and comment on the old one?

**Comment by TheTechnologyStudio** [comment]
I opened a new ticket before I realised I could comment on the closed one sorry.

**Comment by dinger1986** [comment]
ok fair enough, just looking now

**Comment by dinger1986** [comment]
try now please :)

**Comment by TheTechnologyStudio** [comment]
still the exact same error :(

**Comment by dinger1986** [comment]
are you downloading again?

whats the output of `ls -l`

Do `rm installg.*`

Then `wget https://raw.githubusercontent.com/dinger1986/TRMM-Grafana/main/installg.sh`

chmod and run again

**Comment by TheTechnologyStudio** [comment]
seems to be working now. Maybe there was a hidden installg file as I had been manually deleting them before.

also not sure if this error matters. 
https://prnt.sc/WmGykysXQ9HL

**Comment by TheTechnologyStudio** [comment]
https://prnt.sc/3G7z4F9o4iWV

**Comment by TheTechnologyStudio** [comment]
A bunch of permission-denied errors can be accessed https://rmm.thetechnologystudio.com:3000

**Comment by dinger1986** [comment]
> also not sure if this error matters. 
> 
> https://prnt.sc/WmGykysXQ9HL

That errors fine

**Comment by TheTechnologyStudio** [comment]
Accessing the site seems to be a my issue though not the script. http://192.168.1.9:3000/login works fine.

**Comment by TheTechnologyStudio** [comment]
il mark ticket as solved. Thank you.

**Comment by dinger1986** [comment]
> https://prnt.sc/3G7z4F9o4iWV

Might need to manually add the dashboards, or let me check could maybe use the update script to get them.

**Comment by dinger1986** [comment]
Looks like the chown didn't work on /var/lib/grafana/dashboards
