### ISSUE TITLE
Dashboard not loading data.

### ISSUE THREAD

**Issue by TheTechnologyStudio** [dinger1986/TRMM-Grafana#38]
I installed the dashboard and the data source connections and configured the dashboard according to the instructions. I have also tested and made sure the postgresql datasource can connect to the database and it can.

My dashboards are still not loading any data. 
![Screenshot_25](https://github.com/dinger1986/TRMM-Grafana/assets/19619093/20a80ef5-3f33-4854-9af1-be2a0e628026)
![Screenshot_26](https://github.com/dinger1986/TRMM-Grafana/assets/19619093/7ca7f9c9-3903-4c5e-8aaf-b133c948c03f)
![Screenshot_27](https://github.com/dinger1986/TRMM-Grafana/assets/19619093/2af6a3a0-f430-4cc0-82c4-7f7b90271d4d)
![Screenshot_28](https://github.com/dinger1986/TRMM-Grafana/assets/19619093/318c7461-01c7-4007-8a53-e8095a7448b3)

**Comment by dinger1986** [comment]
Is the url right?

**Comment by dinger1986** [comment]
What do the errors show?

**Comment by TheTechnologyStudio** [comment]
Oh permissions error, Status: 500. Message: db query error: pq: permission denied for table agents_agent

**Comment by dinger1986** [comment]
So db user doesn't have permissions. Check the troubleshooting steps

**Comment by TheTechnologyStudio** [comment]
it is working now. Thank you!

**Comment by dinger1986** [comment]
Just needed to reset the dbreader password?

**Comment by TheTechnologyStudio** [comment]
> Just needed to reset the dbreader password?

No i ran these commands: 

GRANT CONNECT ON DATABASE tacticalrmm TO dbreader;
GRANT USAGE ON SCHEMA public to dbreader;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO dbreader;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO dbreader;
quit

but instead of dbreader i changed it to the user i already had, Grafana.

**Comment by TheTechnologyStudio** [comment]
im used to mariadb not postgres . this is my first time with postgres

**Comment by dinger1986** [comment]
Your using mariadb with tactical?

**Comment by TheTechnologyStudio** [comment]
No, but i've never interacted with postgres prior to this

**Comment by dinger1986** [comment]
Ah lol. Cool. Please close this if you are all done. I'd imagine dbreader is created as well so maybe want to delete that user so you don't have users who aren't being used

**Comment by TheTechnologyStudio** [comment]
btw, importing agentdash-v2.json throws this error: Import failed
JSON -> JS Serialization failed: Bad escaped character in JSON at position 54622 

and client dash: Import failed
JSON -> JS Serialization failed: Bad escaped character in JSON at position 41444

**Comment by TheTechnologyStudio** [comment]
the rest seems to work fine.

**Comment by dinger1986** [comment]
You can copy and paste the json directly if that works

**Comment by TheTechnologyStudio** [comment]
will try that.

**Comment by TheTechnologyStudio** [comment]
json validator threw this error: 

Error: Parse error on line 1310:
...true,				"rawSql": "SELECT \n    count(
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

**Comment by dinger1986** [comment]
The dashboards have been provided by others sorry don't know what's wrong with it

**Comment by TheTechnologyStudio** [comment]
Okay, Thank you for trying at least. I will play around with it. and il let u know if i fix it.

**Comment by dinger1986** [comment]
Ok no problems

**Comment by TheTechnologyStudio** [comment]
Hey Dinger, Can you update both agentdash-v2 with https://pastebin.com/F53ZHZEs
and clientdash with https://pastebin.com/fv8W94hv

These are working copies of both scripts.

**Comment by dinger1986** [comment]
Please PR the changes

**Comment by TheTechnologyStudio** [comment]
All i did was pull old versions of the scripts. The one before the latest commit. You are the one listed as creating the scripts I listed above before the one person overwrote that script with some changes.

**Comment by dinger1986** [comment]
lol sorry, I didnt check them, Ill revert them then, thanks!

**Comment by dinger1986** [comment]
I have added as v3 and v1 so leaving the ones working as I think they fix something else that didnt work.

Thanks for your help!
