### ISSUE TITLE
installg.sh won't run on Debian 12

### ISSUE THREAD

**Issue by FreemanTechnologyGroup** [dinger1986/TRMM-Grafana#39]
When I attempt to run installg.sh it detects that I am running Debian GNU/Linux 12 (bookworm) and then says:

Only Ubuntu and Debian are supported
Your system does not appear to be supported

and the script stops.

**Comment by dinger1986** [comment]
Can try and comment it out, or add it and see if it works. I haven't spun up a Debian 12 server yet

**Comment by FreemanTechnologyGroup** [comment]
commenting out the version check worked. Thanks!

**Comment by dinger1986** [comment]
Thanks,

I'll change the script

**Comment by dinger1986** [comment]
updated now
