### ISSUE TITLE
Row Repeat for Multiple Agents

### ISSUE THREAD

**Issue by ventra007** [dinger1986/TRMM-Grafana#41]
Hello,

As the title suggest, I want the ability to repeat rows for certain panels on multiple selected agents.
For now I'm looking at displaying / repeating the CPU panel for certain agents.

I duplicated the existing Agent variable and created it as MultiAgent and ticked the "Multi-value" option, but I don't know how to edit the panel to use the new variable.

Would you be able to assist?

**Comment by dinger1986** [comment]
I cant assist no, I am just maintaining the install etc and keeping that working, any custom dashboards I am happy to take as a PR but not developing them as I dont have time
