### ISSUE TITLE
error in line 1458 of JSON file dashboards/clientdash.json

### ISSUE THREAD

**Issue by tiiilerteee** [dinger1986/TRMM-Grafana#42]
Thank you for these great dashboards for TRMM!

Just FYI: there is an error in line 1458 of JSON file dashboards/clientdash.json

There are special characters that are not properly escaped and need double backslashes

suggested to replace line 1458:

"rawSql": "SELECT \n    count(*) as \"count\",\n    (CASE \n      WHEN wmi_detail->'cpu' IS NOT NULL\n      THEN SUBSTRING(agents_agent.wmi_detail->'cpu'->0->0->>'Name','(?:AMD|\d\dth Gen Intel\(R\)||Intel\(R\)|Intel)(.*)(?:@|Processor||with)')\n      ELSE SUBSTRING(agents_agent.wmi_detail->'cpus'->>0,'(?:AMD|\d\dth Gen Intel\(R\)||Intel\(R\)|Intel)(.*)(?:@|Processor||with)')\n    END) as \"CPU Name\"\nFROM agents_agent\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n  clients_client.name IN ($Client)\n  AND clients_site.name IN ($Sites)\nGroup by \"CPU Name\"\nOrder by \"count\" desc",

with:

"rawSql": "SELECT \n    count(*) as \"count\",\n    (CASE \n      WHEN wmi_detail->'cpu' IS NOT NULL\n      THEN SUBSTRING(agents_agent.wmi_detail->'cpu'->0->0->>'Name','(?:AMD|\\d\\dth Gen Intel\\(R\\)||Intel\\(R\\)|Intel)(.*)(?:@|Processor||with)')\n      ELSE SUBSTRING(agents_agent.wmi_detail->'cpus'->>0,'(?:AMD|\\d\\dth Gen Intel\\(R\\)||Intel\\(R\\)|Intel)(.*)(?:@|Processor||with)')\n    END) as \"CPU Name\"\nFROM agents_agent\n    INNER JOIN clients_site ON agents_agent.site_id = clients_site.id\n    INNER JOIN clients_client ON clients_site.client_id = clients_client.id\nWHERE\n  clients_client.name IN ($Client)\n  AND clients_site.name IN ($Sites)\nGroup by \"CPU Name\"\nOrder by \"count\" desc",

**Comment by dinger1986** [comment]
Please PR and I will accept it
