### ISSUE TITLE
New Install.  Showing no data on the agent dashboard

### ISSUE THREAD

**Issue by rwright-bci** [dinger1986/TRMM-Grafana#44]
Installed Grafana and checked the DB source, and had to create a copy of the dashboard to fix the TacticalURL and GrafanaURL variables (in order to save them).

I can bring up the dashboard but am not seeing any data

Here is a hover over the error:

![image](https://github.com/dinger1986/TRMM-Grafana/assets/83650517/0f014fc5-e707-421b-b707-f7ae43c0c4e1)

Will I need to create a login for each of my techs to be able to view the dashboards in Grafana?  Or is there a way to pass along the Tactical login as the user name?

**Comment by rwright-bci** [comment]
Hovered over the error:
![image](https://github.com/dinger1986/TRMM-Grafana/assets/83650517/e5f806e8-912f-479a-8882-f36bc98dc692)

Also, will I need to set up a user for each tech to be able to login to Grafana or is there a way to pass along the current logged in user?

**Comment by rwright-bci** [comment]
Found an article about disabling TLS for the datasource which brought the graphs to life. 
I'm hoping that create a security issue since everything is happening within the same server?

**Comment by dinger1986** [comment]
are you using localhost? or whats the address you are using? Tbh I use reporting and theres dashboard availability in that so am not doing alot with grafana now.

**Comment by rwright-bci** [comment]
I didn't think of that!  I will check into the reporting module.  Lots to learn! :-)

**Comment by jpfaias** [comment]
Try to change data source from "localhost" to "127.0.0.1"
