### ISSUE TITLE
Same client name, show no data

### ISSUE THREAD

**Issue by icehcp** [dinger1986/TRMM-Grafana#45]
Hi everyone, 

i have 2 different customers in 2 different sites with the same name on a server.
Even if i choose the right site and the right client, the graph show "no data" but as you can see from image, the description report both site and host name, so i think the graph mix data based on the same name.

![2024-03-30 23_11_49-2024-03-30 23_02_35-T-RMM Agent Dashboard Huntech - Tactical - Dashboards - Graf](https://github.com/dinger1986/TRMM-Grafana/assets/120608252/8ed29939-93b7-4d35-b669-f894457b0624)

**Comment by dinger1986** [comment]
If you can fix it please do. I don't know grafana well and infact don't use it at all now reporting has been added to TRMM. I'll close this but if you can fix it feel free to submit a PR
