### ISSUE TITLE
General errors in the Maps section

### ISSUE THREAD

**Issue by sistemmsn** [dinger1986/TRMM-Grafana#47]
Following the procedures that they indicate, I still have not resolved that I bring the data, I will show you
![image](https://github.com/user-attachments/assets/8d0c4e9a-6587-4116-ab81-29cd3bdb1c05)
Linux:
![image](https://github.com/user-attachments/assets/6468e8ba-556e-4e65-8368-77622d0fa31f)
Windows:
![image](https://github.com/user-attachments/assets/6d984721-6804-488d-8910-ce98c7eb0136)
Add the fields in the 3 in site, client and agent and nothing
![image](https://github.com/user-attachments/assets/52b6c744-8ea4-473e-a6ee-63ab8b178ae2)

**Comment by dinger1986** [comment]
Looks similar to #40 and hoping someone else will be able to help as these are community offered dashboards 

Please add any comments there

**Comment by calbertouepb** [comment]
I post my correction to get dashboard working in #40 .Thanks.

**Comment by tricky1024** [comment]
I have the same issue, as the initial screen prints, been looking and trying to debug for a couple of days, was there ever a resolution to why we got the errors: 

Linux: urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
Windows: urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>
